Revert "TEST why doesn't this work"
This reverts commit 90b7022647138380bb64528b81610287fe17d06b.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -18,6 +18,14 @@ jobs:
       - name: Get clean version
         run: |
           echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
+      - name: Check that version matches
+        run: |
+          if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./ -name mod.json))" != "${{ env.cleanVersion }}" ]]; then
+            echo "::debug::${{env.cleanVersion}}"
+            echo "::debug::$(cat $(find ./ -name mod.json ))"
+            echo "::error::Version in mod.json does not match tag version"
+            exit 1
+          fi
   publish:
     runs-on: ubuntu-latest
     needs: verify
